name: Android CI / CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Setup and build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run unit tests
      run: ./gradlew test
      
    - name: Generate debug APK
      run: ./gradlew build
  
  upload:
    needs: [ build ]
    name: Upload artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Upload debug APK
        uses: actions/upload-artifact@v4.3.3
        with:
          name: build
          path: app/build/outputs/apk/debug/app-debug.apk
